# -*- coding: utf-8 -*-
"""UV_notify.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f8A6ltXU8z9XsUgOfYki4DI9dmHosrQv
"""

import requests

#UV指数の取得
def get_uv_index(lat, lon, token):
    url = f"https://api.openuv.io/api/v1/uv?lat={lat}&lng={lon}"
    headers = {"x-access-token": token}
    response = requests.get(url, headers=headers)
    data = response.json()
    uv = data["result"]["uv"]
    uv_max = data["result"]["uv_max"]
    return uv, uv_max

# import os
# api_key = os.environ["UV_API"]

# import openai
# from google.colab import userdata
# openai.api_key = userdata.get('UV_API')


# # 例：東京の緯度経度
# message = get_uv_index(35.6895, 139.6917, UV_API)


from google.colab import userdata
uv_api = userdata.get('UV_API')

# message = get_uv_index(35.6895, 139.6917, uv_api)

# UV取得
uv, uv_max = get_uv_index(43.0621, 151.3544, uv_api)

# print (message)



import requests

def send_discord_webhook(webhook_url, message):
    payload = {"content": message}
    headers = {"Content-Type": "application/json"}
    response = requests.post(webhook_url, json=payload, headers=headers)
    return response.status_code



webhook_url= "https://discordapp.com/api/webhooks/1397136606628151316/v0UAVc7Od_S8h9nOCXGr6xjdcZvkJ3WdYig6rsQdLjazH2A8Iyqqp_KLzHLFK-MQuEC8"

def uv_level_info(uv):
    if uv <= 2:
        return "🧢 安心レベル：UV指数は低め。特別な対策は不要です。"
    elif uv <= 5:
        return "🌤 注意レベル：じわじわ紫外線が来てます。帽子や日焼け止めを！"
    elif uv <= 7:
        return "☀️ 高めレベル：UV指数が高いです。日陰や対策を心がけて！"
    elif uv <= 10:
        return "🔥 強烈レベル：紫外線が強い！サングラス・長袖必須です。"
    else:
        return "🚨 危険レベル：UV指数が非常に高い！なるべく外出を控えて！"

import requests
from datetime import datetime, timezone, timedelta

def send_discord_embed(webhook_url, uv_value, uv_max, location="東京"):
    embed = {
        "title": f"☀️ {location}のUV指数レポート",
        "description": f"現在のUV指数：**{uv_value:.1f}**\n本日の最大UV指数：**{uv_max:.1f}**\n\n{uv_level_info(uv_value)}",
        "color": 16763904,  # オレンジ系（16進カラーコード）
        "footer": {"text": "肌を守って、賢くUV対策！"},
        "timestamp": datetime.now(timezone(timedelta(hours=9))).isoformat()

    }

    payload = {
        "username": "UV Forecast Bot",
        "embeds": [embed]
    }

    headers = {"Content-Type": "application/json"}
    response = requests.post(webhook_url, json=payload, headers=headers)
    return response.status_code



status = send_discord_embed(webhook_url, uv, uv_max, location="札幌")

if status == 204:
    print("Discordに通知できました！🎉")
else:
    print(f"通知に失敗しました（status: {status}）")